version: "3"
networks:
    expense:
volumes:
    mysql: # it is equavalent to docker volume create mysql
services:
    mysql:
        image: mysql:v1
        container_name: mysql
        volumes:
        - mysql:/var/lib/mysql # -v mysql:/var/lib/mysql
    backend:
        image: backend:v1
        contaciner_name: backend
        command: sh -c "sleep 5 && node /opt/server/index.js"
        depends_on:
        - mysql
    frontend:
        image: frontend:v1
        contaciner_name: frontend
        ports:
        - 80:80
        depends_on:
        - backend



